name: Build main.cpp in cvast

on:
  push:
  pull_request:
    paths:
      - cvast/main.cpp
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ python3.12-dev

      - name: Compile using g++ with Python 3.12
        working-directory: ./cvast
        run: |
          g++ -g -std=c++20 -I/usr/include/python3.12 main.cpp -o main -L/usr/lib -lpython3.12
