name: Build main.cpp in cvast

on:
  push:
    paths:
      - cvast/main.cpp
  pull_request:
    paths:
      - cvast/main.cpp
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup C++ environment
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ python3-dev

      - name: Compile main.cpp
        working-directory: ./cvast
        run: g++ -o main main.cpp -I/usr/include/python3.13 -lpython3.13

      - name: Run the compiled program (Optional)
        working-directory: ./cvast
        run: ./main
